import React, { useState, useMemo, useEffect } from 'react';
import { Form, Lead } from '@/types';
import { ArrowLeft, Users, DollarSign, TrendingUp, MessageSquare, Sparkles, Loader2, Download, Calendar, Target, Filter, X, Mail, Phone, FileText, Edit2, Plus, Trash2, Check, AlertCircle } from 'lucide-react';
import { SupabaseClient } from '@supabase/supabase-js';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import { GoogleGenerativeAI } from "@google/generative-ai";
import ReactMarkdown from 'react-markdown';

interface Product {
  id: string;
  name: string;
  value: number;
}

interface FormReportProps {
  formId: string;
  forms: Form[];
  leads: Lead[];
  onBack: () => void;
  supabase?: SupabaseClient;
  userId?: string;
  onLeadUpdate?: (leadId: string, updatedData: any) => void;
}

const FormReport: React.FC<FormReportProps> = ({ formId, forms, leads, onBack, supabase, userId, onLeadUpdate }) => {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<string | null>(null);
  
  // Estados para edição de produtos recomendados
  const [products, setProducts] = useState<Product[]>([]);
  const [isEditingProducts, setIsEditingProducts] = useState(false);
  const [editedProducts, setEditedProducts] = useState<{id: string; name: string; value: number}[]>([]);
  const [wasManuallyEdited, setWasManuallyEdited] = useState(false);
  const [isSavingProducts, setIsSavingProducts] = useState(false);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);

  // 1. Get Form Data
  const form = forms.find(f => f.id === formId);
  
  // 2. Filter Leads generated by this Form
  const formLeads = useMemo(() => {
    if (!form) return [];
    return leads.filter(l => {
        // Strict match by ID if available, otherwise loose match by name (legacy)
        if (l.formId && form.id) {
            return l.formId === form.id;
        }
        return l.formSource === form.name;
    });
  }, [form, leads]);

  // 3. Calculate Metrics
  const totalLeads = formLeads.length;
  const totalValue = formLeads.reduce((acc, curr) => acc + curr.value, 0);
  const avgTicket = totalLeads > 0 ? totalValue / totalLeads : 0;
  
  const leadsSold = formLeads.filter(l => l.status === 'Vendido').length;
  const conversionRate = totalLeads > 0 ? (leadsSold / totalLeads) * 100 : 0;

  // Status Distribution Data
  const statusCounts = formLeads.reduce((acc, lead) => {
    acc[lead.status] = (acc[lead.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const funnelData = [
    { name: 'Novo', value: statusCounts['Novo'] || 0, color: '#6ee7b7' },
    { name: 'Em Contato', value: statusCounts['Em Contato'] || 0, color: '#34d399' },
    { name: 'Negoc.', value: statusCounts['Negociação'] || 0, color: '#10b981' },
    { name: 'Vendido', value: statusCounts['Vendido'] || 0, color: '#059669' },
    { name: 'Perdido', value: statusCounts['Perdido'] || 0, color: '#ef4444' },
  ].filter(d => d.value > 0);

  // Carregar produtos disponíveis
  useEffect(() => {
    const fetchProducts = async () => {
      if (!supabase || !userId) {
        console.log('FormReport: supabase ou userId não disponível', { supabase: !!supabase, userId });
        return;
      }
      try {
        console.log('FormReport: Carregando produtos para userId:', userId);
        const { data, error } = await supabase
          .from('products_services')
          .select('id, name, value')
          .eq('user_id', userId);
        
        if (error) {
          console.error('FormReport: Erro ao carregar produtos:', error);
          return;
        }
        
        if (data) {
          console.log('FormReport: Produtos carregados:', data.length, data);
          setProducts(data);
        }
      } catch (err) {
        console.error('FormReport: Exceção ao carregar produtos:', err);
      }
    };
    fetchProducts();
  }, [supabase, userId]);

  // Inicializar produtos editados quando seleciona um lead
  useEffect(() => {
    if (selectedLead?.answers?._ai_analysis) {
      const analysis = selectedLead.answers._ai_analysis;
      // Verificar se já foi editado manualmente
      setWasManuallyEdited(analysis.manually_edited || false);
      // Carregar produtos recomendados (pode ser um ou múltiplos)
      if (analysis.recommended_products && Array.isArray(analysis.recommended_products)) {
        setEditedProducts(analysis.recommended_products);
      } else if (analysis.suggested_product) {
        setEditedProducts([{
          id: 'original',
          name: analysis.suggested_product,
          value: analysis.suggested_value || 0
        }]);
      } else {
        setEditedProducts([]);
      }
    }
  }, [selectedLead]);

  // Funções de edição de produtos
  const handleAddProduct = (product: Product) => {
    if (!editedProducts.find(p => p.id === product.id)) {
      setEditedProducts([...editedProducts, { id: product.id, name: product.name, value: product.value }]);
    }
  };

  const handleRemoveProduct = (productId: string) => {
    setEditedProducts(editedProducts.filter(p => p.id !== productId));
  };

  const handleSaveProductEdits = async () => {
    if (!selectedLead || !supabase) return;
    setIsSavingProducts(true);
    try {
      const totalValue = editedProducts.reduce((sum, p) => sum + p.value, 0);
      const updatedAnalysis = {
        ...selectedLead.answers._ai_analysis,
        recommended_products: editedProducts,
        suggested_product: editedProducts.map(p => p.name).join(', '),
        suggested_value: totalValue,
        manually_edited: true,
        edited_at: new Date().toISOString()
      };

      const updatedAnswers = {
        ...selectedLead.answers,
        _ai_analysis: updatedAnalysis
      };

      const { error } = await supabase
        .from('leads')
        .update({ answers: updatedAnswers, value: totalValue })
        .eq('id', selectedLead.id);

      if (!error) {
        setWasManuallyEdited(true);
        setIsEditingProducts(false);
        // Atualizar lead local
        if (onLeadUpdate) {
          onLeadUpdate(selectedLead.id, { answers: updatedAnswers, value: totalValue });
        }
        // Atualizar selectedLead
        setSelectedLead({
          ...selectedLead,
          answers: updatedAnswers,
          value: totalValue
        });
      }
    } catch (err) {
      console.error('Erro ao salvar edições:', err);
    } finally {
      setIsSavingProducts(false);
    }
  };

  // 4. AI Analysis Handler
  const handleAnalyzeLeads = async () => {
    if (formLeads.length === 0) return;
    
    setIsAnalyzing(true);
    try {
      const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
      if (apiKey) {
        const ai = new GoogleGenerativeAI(apiKey);
        const model = ai.getGenerativeModel({ model: 'gemini-2.0-flash' });
        
        const leadsSummary = formLeads
          .map(l => `- ${l.name}: Status "${l.status}", Valor R$${l.value}`)
          .join('\n');

        const prompt = `
          Atue como um Gerente de Vendas e Growth.
          Analise a performance do formulário de captação "${form?.name}".
          
          DADOS DOS LEADS GERADOS POR ESTE FORMULÁRIO:
          Total Leads: ${totalLeads}
          Valor Total em Pipeline: R$ ${totalValue}
          Taxa de Conversão (Vendas): ${conversionRate.toFixed(1)}%
          
          LISTA DE LEADS RECENTES:
          ${leadsSummary.substring(0, 1000)}... (amostra)
          
          TAREFA:
          Forneça um relatório estratégico em Markdown com:
          1. **Qualidade dos Leads**: O formulário está trazendo clientes de alto valor?
          2. **Gargalos de Funil**: Onde os leads estão travando (ex: muitos em 'Novo' sem contato)?
          3. **Sugestão de Otimização**: Uma mudança no formulário ou na abordagem de vendas para melhorar a conversão.
          
          Seja conciso e focado em ROI.
        `;

        const result = await model.generateContent(prompt);

        setAiAnalysis(result.response.text() || "Não foi possível gerar a análise.");
      } else {
        // Mock fallback
        await new Promise(r => setTimeout(r, 2000));
        setAiAnalysis(`**Análise Simulada (Sem API Key):**\n\nO formulário "${form?.name}" gerou **R$ ${totalValue.toLocaleString()}** em oportunidades. A taxa de conversão de **${conversionRate.toFixed(1)}%** indica que os leads são qualificados, mas há muitos parados na fase inicial.`);
      }
    } catch (error) {
      console.error(error);
      setAiAnalysis("Erro ao processar análise com IA.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Helper to resolve question text
  const getQuestionText = (questionId: string) => {
    const question = form?.questions.find(q => q.id === questionId);
    return question ? question.text : `Pergunta desconhecida (${questionId})`;
  };

  if (!form) return <div>Formulário não encontrado</div>;

  return (
    <div className="p-8 min-h-screen bg-gray-50 relative">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-gray-200 rounded-full transition-colors">
            <ArrowLeft size={24} className="text-gray-600" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
              {form.name}
              <span className={`text-xs px-2 py-1 rounded-full border ${form.active ? 'bg-green-50 text-green-700 border-green-200' : 'bg-gray-100 text-gray-600 border-gray-200'}`}>
                {form.active ? 'Ativo' : 'Inativo'}
              </span>
            </h1>
            <p className="text-gray-500 text-sm mt-1">Performance de captação e qualificação</p>
          </div>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 text-sm font-medium">
          <Download size={16} /> Exportar CSV
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Total Leads</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">{totalLeads}</h3>
            </div>
            <div className="p-2 bg-blue-50 rounded-lg text-blue-600">
              <Users size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Valor em Pipeline</p>
              <h3 className="text-3xl font-bold text-green-600 mt-2">
                {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(totalValue)}
              </h3>
            </div>
            <div className="p-2 bg-green-50 rounded-lg text-green-600">
              <DollarSign size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Ticket Médio</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">
                 {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(avgTicket)}
              </h3>
            </div>
            <div className="p-2 bg-gray-50 rounded-lg text-gray-400">
              <Target size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Taxa Conversão</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">{conversionRate.toFixed(1)}%</h3>
            </div>
            <div className="p-2 bg-purple-50 rounded-lg text-purple-600">
              <TrendingUp size={20} />
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
        {/* Funnel Chart */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-bold text-gray-900 mb-4">Status do Funil</h3>
          <div className="h-64 flex items-center justify-center relative">
             <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={funnelData}
                    innerRadius={60}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {funnelData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute text-center">
                <span className="block text-2xl font-bold text-gray-800">{totalLeads}</span>
                <span className="text-xs text-gray-500 uppercase">Leads</span>
              </div>
          </div>
          <div className="flex flex-wrap justify-center gap-3 mt-2">
              {funnelData.map((d) => (
                <div key={d.name} className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: d.color }}></div>
                  <span className="text-xs text-gray-600">{d.name}</span>
                </div>
              ))}
            </div>
        </div>

        {/* AI Analysis Section */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 lg:col-span-2 flex flex-col">
          <div className="flex justify-between items-center mb-6">
            <div className="flex items-center gap-2 text-purple-700">
              <div className="p-1.5 bg-purple-100 rounded-lg">
                <Sparkles size={18} />
              </div>
              <h3 className="text-lg font-bold">Análise de Qualidade de Leads</h3>
            </div>
            {!aiAnalysis && (
              <button 
                onClick={handleAnalyzeLeads}
                disabled={isAnalyzing || totalLeads === 0}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium flex items-center gap-2 transition-all"
              >
                {isAnalyzing ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
                {isAnalyzing ? 'Analisando...' : 'Gerar Relatório com IA'}
              </button>
            )}
          </div>

          <div className="flex-1 bg-purple-50/50 rounded-xl p-6 border border-purple-100 overflow-y-auto max-h-[300px]">
            {aiAnalysis ? (
              <div className="prose prose-sm prose-purple max-w-none">
                <ReactMarkdown>{aiAnalysis}</ReactMarkdown>
                <div className="mt-4 flex justify-end">
                   <button onClick={() => setAiAnalysis(null)} className="text-xs text-purple-600 hover:underline">Regerar análise</button>
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center text-gray-500">
                <Filter size={32} className="mb-2 text-gray-300" />
                <p>Clique no botão para analisar o perfil e valor dos leads captados.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Leads Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-100">
          <h3 className="font-bold text-gray-900">Leads Captados ({totalLeads})</h3>
        </div>
        <table className="w-full text-left">
          <thead className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
            <tr>
              <th className="px-6 py-3 font-medium">Nome</th>
              <th className="px-6 py-3 font-medium">Email</th>
              <th className="px-6 py-3 font-medium">Status</th>
              <th className="px-6 py-3 font-medium">Valor Oportunidade</th>
              <th className="px-6 py-3 font-medium">Data</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {formLeads.map((lead) => (
              <tr 
                key={lead.id} 
                onClick={() => setSelectedLead(lead)}
                className="hover:bg-gray-50 transition-colors cursor-pointer group"
              >
                <td className="px-6 py-4">
                  <span className="font-medium text-gray-900 group-hover:text-primary-600 transition-colors">{lead.name}</span>
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  {lead.email}
                </td>
                <td className="px-6 py-4">
                  <span className={`text-xs px-2 py-1 rounded-full font-medium ${
                     lead.status === 'Novo' ? 'bg-blue-100 text-blue-700' :
                     lead.status === 'Vendido' ? 'bg-green-100 text-green-700' :
                     lead.status === 'Perdido' ? 'bg-red-100 text-red-700' :
                     'bg-yellow-100 text-yellow-700'
                  }`}>
                    {lead.status}
                  </span>
                </td>
                <td className="px-6 py-4 font-medium text-gray-700">
                  {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(lead.value)}
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  <div className="flex items-center gap-1">
                    <Calendar size={14} />
                    {new Date(lead.date || Date.now()).toLocaleDateString('pt-BR')}
                  </div>
                </td>
              </tr>
            ))}
            {formLeads.length === 0 && (
              <tr>
                <td colSpan={5} className="px-6 py-12 text-center text-gray-500">
                  Nenhum lead captado por este formulário ainda.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Lead Details Panel */}
      {selectedLead && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30">
          {/* Full Screen Panel */}
          <div className="w-full h-full bg-white shadow-2xl flex flex-col animate-in fade-in duration-300">
            <div className="p-4 border-b border-gray-100 flex justify-between items-start bg-gray-50 sticky top-0 z-10">
              <div>
                <h2 className="text-lg font-bold text-gray-900">{selectedLead.name}</h2>
                <div className="flex items-center gap-2 mt-2">
                  <span className={`px-3 py-1 rounded-full text-sm font-bold ${
                     selectedLead.status === 'Novo' ? 'bg-blue-100 text-blue-700' :
                     selectedLead.status === 'Vendido' ? 'bg-green-100 text-green-700' :
                     selectedLead.status === 'Perdido' ? 'bg-red-100 text-red-700' :
                     'bg-yellow-100 text-yellow-700'
                  }`}>
                    {selectedLead.status}
                  </span>
                  <span className="text-sm text-gray-500">
                    {new Date(selectedLead.date || Date.now()).toLocaleDateString('pt-BR', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                  </span>
                </div>
              </div>
              <button onClick={() => setSelectedLead(null)} className="text-gray-400 hover:text-gray-600 bg-white rounded-full p-2 hover:bg-gray-200 transition-colors">
                <X size={20} />
              </button>
            </div>

            <div className="p-6 overflow-y-auto flex-1">
              <div className="max-w-4xl mx-auto space-y-6">
              {/* Contact Info */}
              <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-xl border border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="bg-white p-2 rounded-lg text-gray-500"><Mail size={18} /></div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase font-semibold">Email</p>
                    <p className="text-sm text-gray-800">{selectedLead.email || 'Não informado'}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <div className="bg-white p-2 rounded-lg text-green-600"><DollarSign size={18} /></div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase font-semibold">Valor Oportunidade</p>
                    <p className="text-sm font-bold text-green-700">
                      {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(selectedLead.value)}
                    </p>
                  </div>
                </div>
              </div>

              {/* AI Analysis Section */}
              {selectedLead.answers?._ai_analysis && (
                <div className="bg-gradient-to-br from-purple-50 to-blue-50 border-2 border-purple-200 rounded-xl p-6">
                  <div className="flex items-center gap-2 mb-4">
                    <Sparkles size={20} className="text-purple-600" />
                    <h3 className="text-lg font-bold text-purple-900">Análise de Oportunidade (IA)</h3>
                  </div>
                  
                  <div className="space-y-4">
                    {/* Produto Sugerido e Valor - EDITÁVEL */}
                    <div className="bg-white rounded-lg p-4 border border-purple-100">
                      {/* Cabeçalho com botão de editar */}
                      <div className="flex justify-between items-center mb-3">
                        <div className="flex items-center gap-2">
                          <p className="text-xs text-gray-500 font-semibold uppercase">Produtos Recomendados</p>
                          {wasManuallyEdited && (
                            <span className="flex items-center gap-1 px-2 py-0.5 bg-amber-100 text-amber-700 text-xs font-medium rounded-full">
                              <AlertCircle size={12} />
                              Editado manualmente
                            </span>
                          )}
                        </div>
                        {!isEditingProducts ? (
                          <button
                            onClick={() => setIsEditingProducts(true)}
                            className="flex items-center gap-1 px-3 py-1.5 text-purple-600 hover:bg-purple-50 rounded-lg text-sm font-medium transition-colors"
                          >
                            <Edit2 size={14} />
                            Editar
                          </button>
                        ) : (
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => {
                                setIsEditingProducts(false);
                                // Resetar para valores originais
                                if (selectedLead?.answers?._ai_analysis?.recommended_products) {
                                  setEditedProducts(selectedLead.answers._ai_analysis.recommended_products);
                                }
                              }}
                              className="px-3 py-1.5 text-gray-600 hover:bg-gray-100 rounded-lg text-sm font-medium transition-colors"
                            >
                              Cancelar
                            </button>
                            <button
                              onClick={handleSaveProductEdits}
                              disabled={isSavingProducts}
                              className="flex items-center gap-1 px-3 py-1.5 bg-purple-600 text-white hover:bg-purple-700 rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
                            >
                              {isSavingProducts ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />}
                              Salvar
                            </button>
                          </div>
                        )}
                      </div>

                      {/* Modo Visualização */}
                      {!isEditingProducts && (
                        <>
                          <div className="flex justify-between items-start mb-2">
                            <div>
                              <p className="text-lg font-bold text-gray-900">
                                {editedProducts.length > 0 
                                  ? editedProducts.map(p => p.name).join(', ')
                                  : selectedLead.answers._ai_analysis.suggested_product
                                }
                              </p>
                            </div>
                            <div className="text-right">
                              <p className="text-xs text-gray-500 font-semibold uppercase">Valor Estimado</p>
                              <p className="text-2xl font-bold text-green-600">
                                {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(
                                  editedProducts.length > 0 
                                    ? editedProducts.reduce((sum, p) => sum + p.value, 0)
                                    : selectedLead.answers._ai_analysis.suggested_value || 0
                                )}
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2 mt-3">
                            <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                              selectedLead.answers._ai_analysis.classification === 'opportunity' ? 'bg-green-100 text-green-700' :
                              selectedLead.answers._ai_analysis.classification === 'risk' ? 'bg-red-100 text-red-700' :
                              'bg-yellow-100 text-yellow-700'
                            }`}>
                              {selectedLead.answers._ai_analysis.classification === 'opportunity' ? '✅ Alta Oportunidade' :
                               selectedLead.answers._ai_analysis.classification === 'risk' ? '⚠️ Risco' :
                               '🔍 Monitorar'}
                            </span>
                            <span className="text-xs text-gray-600">
                              Confiança: {Math.round((selectedLead.answers._ai_analysis.confidence || 0) * 100)}%
                            </span>
                          </div>
                        </>
                      )}

                      {/* Modo Edição */}
                      {isEditingProducts && (
                        <div className="space-y-4">
                          {/* Produtos selecionados */}
                          <div>
                            <p className="text-sm font-medium text-gray-700 mb-2">Produtos selecionados:</p>
                            {editedProducts.length === 0 ? (
                              <p className="text-sm text-gray-400 italic">Nenhum produto selecionado</p>
                            ) : (
                              <div className="space-y-2">
                                {editedProducts.map((product) => (
                                  <div key={product.id} className="flex items-center justify-between bg-purple-50 p-3 rounded-lg border border-purple-200">
                                    <div>
                                      <p className="font-medium text-gray-900">{product.name}</p>
                                      <p className="text-sm text-green-600 font-bold">
                                        {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(product.value)}
                                      </p>
                                    </div>
                                    <button
                                      onClick={() => handleRemoveProduct(product.id)}
                                      className="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                                    >
                                      <Trash2 size={16} />
                                    </button>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>

                          {/* Adicionar produtos */}
                          <div>
                            <p className="text-sm font-medium text-gray-700 mb-2">Adicionar produto:</p>
                            {products.length === 0 ? (
                              <p className="text-sm text-gray-400 italic">Nenhum produto cadastrado. Cadastre produtos em "Produtos e Serviços".</p>
                            ) : (
                              <div className="grid grid-cols-2 gap-2 max-h-48 overflow-y-auto">
                                {products.filter(p => !editedProducts.find(ep => ep.id === p.id)).map((product) => (
                                  <button
                                    key={product.id}
                                    onClick={() => handleAddProduct(product)}
                                    className="flex items-center gap-2 p-2 text-left border border-gray-200 rounded-lg hover:border-purple-300 hover:bg-purple-50 transition-colors"
                                  >
                                    <Plus size={14} className="text-purple-500 flex-shrink-0" />
                                    <div className="min-w-0">
                                      <p className="text-sm font-medium text-gray-900 truncate">{product.name}</p>
                                      <p className="text-xs text-green-600">
                                        {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(product.value)}
                                      </p>
                                    </div>
                                  </button>
                                ))}
                              </div>
                            )}
                          </div>

                          {/* Total */}
                          <div className="pt-3 border-t border-gray-200">
                            <div className="flex justify-between items-center">
                              <span className="text-sm font-medium text-gray-700">Valor Total:</span>
                              <span className="text-xl font-bold text-green-600">
                                {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(
                                  editedProducts.reduce((sum, p) => sum + p.value, 0)
                                )}
                              </span>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>

                    {/* Raciocínio */}
                    <div className="bg-white rounded-lg p-4 border border-purple-100">
                      <p className="text-xs text-gray-500 font-semibold uppercase mb-2">🧠 Raciocínio da IA</p>
                      <p className="text-gray-700 leading-relaxed">{selectedLead.answers._ai_analysis.reasoning}</p>
                    </div>

                    {/* Insights do Cliente */}
                    {selectedLead.answers._ai_analysis.client_insights && selectedLead.answers._ai_analysis.client_insights.length > 0 && (
                      <div className="bg-white rounded-lg p-4 border border-purple-100">
                        <p className="text-xs text-gray-500 font-semibold uppercase mb-3">💡 Insights do Cliente</p>
                        <ul className="space-y-2">
                          {selectedLead.answers._ai_analysis.client_insights.map((insight: string, idx: number) => (
                            <li key={idx} className="flex items-start gap-2">
                              <span className="text-purple-500 mt-1">•</span>
                              <span className="text-gray-700">{insight}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Script de Vendas */}
                    {selectedLead.answers._ai_analysis.sales_script && (
                      <div className="bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg p-4 border-2 border-green-200">
                        <p className="text-xs text-green-700 font-semibold uppercase mb-2 flex items-center gap-1">
                          <Target size={14} /> Script de Abordagem
                        </p>
                        <p className="text-gray-800 font-medium italic leading-relaxed">
                          "{selectedLead.answers._ai_analysis.sales_script}"
                        </p>
                      </div>
                    )}

                    {/* Próximos Passos */}
                    {selectedLead.answers._ai_analysis.next_steps && selectedLead.answers._ai_analysis.next_steps.length > 0 && (
                      <div className="bg-white rounded-lg p-4 border border-purple-100">
                        <p className="text-xs text-gray-500 font-semibold uppercase mb-3">✅ Próximos Passos Recomendados</p>
                        <ol className="space-y-2">
                          {selectedLead.answers._ai_analysis.next_steps.map((step: string, idx: number) => (
                            <li key={idx} className="flex items-start gap-2">
                              <span className="bg-purple-100 text-purple-700 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">{idx + 1}</span>
                              <span className="text-gray-700">{step}</span>
                            </li>
                          ))}
                        </ol>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Form Answers */}
              {selectedLead.answers && Object.keys(selectedLead.answers).length > 0 && (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <FileText size={18} className="text-gray-400" />
                    <h3 className="text-sm font-bold text-gray-900 uppercase">Respostas do Formulário</h3>
                  </div>
                  <div className="space-y-3">
                    {Object.entries(selectedLead.answers).filter(([questionId]) => questionId !== '_ai_analysis').map(([questionId, answerData]: [string, any]) => (
                      <div key={questionId} className="border border-gray-200 rounded-lg p-4 bg-white">
                        <p className="text-xs text-gray-500 font-semibold mb-1.5">{getQuestionText(questionId)}</p>
                        <div className="flex justify-between items-start">
                          <p className="text-gray-900 font-medium text-lg">{Array.isArray(answerData.value) ? answerData.value.join(', ') : answerData.value}</p>
                          {answerData.optionSelected?.value > 0 && (
                            <span className="text-xs font-bold text-green-600 bg-green-50 px-2 py-1 rounded border border-green-100">
                              + R$ {answerData.optionSelected.value}
                            </span>
                          )}
                        </div>
                        {answerData.followUps && Object.values(answerData.followUps).some(text => text) && (
                          <div className="mt-2 pt-2 border-t border-gray-100">
                            {Object.entries(answerData.followUps).map(([optId, text]) => 
                              text ? (
                                <div key={optId}>
                                  <p className="text-xs text-gray-500 font-medium italic">Informação adicional:</p>
                                  <p className="text-gray-800 font-medium pl-2 border-l-2 border-gray-200 mt-1">{text as string}</p>
                                </div>
                              ) : null
                            )}
                          </div>
                        )}
                        {answerData.optionSelected?.script && (
                          <div className="mt-2 pt-2 border-t border-gray-100">
                            <p className="text-xs text-purple-600 font-medium italic flex items-center gap-1">
                              <Sparkles size={12} /> Dica de Venda: "{answerData.optionSelected.script}"
                            </p>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
              
              {!selectedLead.answers && (
                <div className="text-center py-8 text-gray-400 bg-gray-50 rounded-xl border border-dashed border-gray-200">
                  <p>Detalhes das respostas não disponíveis para este lead antigo.</p>
                </div>
              )}
              </div>
            </div>

            <div className="p-4 bg-gray-50 border-t border-gray-100 text-right flex-shrink-0">
              <button 
                onClick={() => setSelectedLead(null)}
                className="px-4 py-2 bg-white border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-100 font-medium"
              >
                Fechar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FormReport;
