
import React, { useState, useMemo } from 'react';
import { Form, Lead } from '@/types';
import { ArrowLeft, Users, DollarSign, TrendingUp, MessageSquare, Sparkles, Loader2, Download, Calendar, Target, Filter, X, Mail, Phone, FileText } from 'lucide-react';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import { GoogleGenerativeAI } from "@google/generative-ai";
import ReactMarkdown from 'react-markdown';

interface FormReportProps {
  formId: string;
  forms: Form[];
  leads: Lead[];
  onBack: () => void;
}

const FormReport: React.FC<FormReportProps> = ({ formId, forms, leads, onBack }) => {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<string | null>(null);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);

  // 1. Get Form Data
  const form = forms.find(f => f.id === formId);
  
  // 2. Filter Leads generated by this Form
  const formLeads = useMemo(() => {
    if (!form) return [];
    return leads.filter(l => {
        // Strict match by ID if available, otherwise loose match by name (legacy)
        if (l.formId && form.id) {
            return l.formId === form.id;
        }
        return l.formSource === form.name;
    });
  }, [form, leads]);

  // 3. Calculate Metrics
  const totalLeads = formLeads.length;
  const totalValue = formLeads.reduce((acc, curr) => acc + curr.value, 0);
  const avgTicket = totalLeads > 0 ? totalValue / totalLeads : 0;
  
  const leadsSold = formLeads.filter(l => l.status === 'Vendido').length;
  const conversionRate = totalLeads > 0 ? (leadsSold / totalLeads) * 100 : 0;

  // Status Distribution Data
  const statusCounts = formLeads.reduce((acc, lead) => {
    acc[lead.status] = (acc[lead.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const funnelData = [
    { name: 'Novo', value: statusCounts['Novo'] || 0, color: '#6ee7b7' },
    { name: 'Em Contato', value: statusCounts['Em Contato'] || 0, color: '#34d399' },
    { name: 'Negoc.', value: statusCounts['Negociação'] || 0, color: '#10b981' },
    { name: 'Vendido', value: statusCounts['Vendido'] || 0, color: '#059669' },
    { name: 'Perdido', value: statusCounts['Perdido'] || 0, color: '#ef4444' },
  ].filter(d => d.value > 0);

  // 4. AI Analysis Handler
  const handleAnalyzeLeads = async () => {
    if (formLeads.length === 0) return;
    
    setIsAnalyzing(true);
    try {
      const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
      if (apiKey) {
        const ai = new GoogleGenerativeAI(apiKey);
        
        const leadsSummary = formLeads
          .map(l => `- ${l.name}: Status "${l.status}", Valor R$${l.value}`)
          .join('\n');

        const prompt = `
          Atue como um Gerente de Vendas e Growth.
          Analise a performance do formulário de captação "${form?.name}".
          
          DADOS DOS LEADS GERADOS POR ESTE FORMULÁRIO:
          Total Leads: ${totalLeads}
          Valor Total em Pipeline: R$ ${totalValue}
          Taxa de Conversão (Vendas): ${conversionRate.toFixed(1)}%
          
          LISTA DE LEADS RECENTES:
          ${leadsSummary.substring(0, 1000)}... (amostra)
          
          TAREFA:
          Forneça um relatório estratégico em Markdown com:
          1. **Qualidade dos Leads**: O formulário está trazendo clientes de alto valor?
          2. **Gargalos de Funil**: Onde os leads estão travando (ex: muitos em 'Novo' sem contato)?
          3. **Sugestão de Otimização**: Uma mudança no formulário ou na abordagem de vendas para melhorar a conversão.
          
          Seja conciso e focado em ROI.
        `;

        const result = await model.generateContent({
          // FIX: Upgraded model to 'gemini-3-pro-preview' for complex strategic reporting.
          contents: prompt,
        });

        setAiAnalysis(result.response.text() || "Não foi possível gerar a análise.");
      } else {
        // Mock fallback
        await new Promise(r => setTimeout(r, 2000));
        setAiAnalysis(`**Análise Simulada (Sem API Key):**\n\nO formulário "${form?.name}" gerou **R$ ${totalValue.toLocaleString()}** em oportunidades. A taxa de conversão de **${conversionRate.toFixed(1)}%** indica que os leads são qualificados, mas há muitos parados na fase inicial.`);
      }
    } catch (error) {
      console.error(error);
      setAiAnalysis("Erro ao processar análise com IA.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Helper to resolve question text
  const getQuestionText = (questionId: string) => {
    const question = form?.questions.find(q => q.id === questionId);
    return question ? question.text : `Pergunta desconhecida (${questionId})`;
  };

  if (!form) return <div>Formulário não encontrado</div>;

  return (
    <div className="p-8 min-h-screen bg-gray-50 relative">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-gray-200 rounded-full transition-colors">
            <ArrowLeft size={24} className="text-gray-600" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
              {form.name}
              <span className={`text-xs px-2 py-1 rounded-full border ${form.active ? 'bg-green-50 text-green-700 border-green-200' : 'bg-gray-100 text-gray-600 border-gray-200'}`}>
                {form.active ? 'Ativo' : 'Inativo'}
              </span>
            </h1>
            <p className="text-gray-500 text-sm mt-1">Performance de captação e qualificação</p>
          </div>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 text-sm font-medium">
          <Download size={16} /> Exportar CSV
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Total Leads</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">{totalLeads}</h3>
            </div>
            <div className="p-2 bg-blue-50 rounded-lg text-blue-600">
              <Users size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Valor em Pipeline</p>
              <h3 className="text-3xl font-bold text-green-600 mt-2">
                {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(totalValue)}
              </h3>
            </div>
            <div className="p-2 bg-green-50 rounded-lg text-green-600">
              <DollarSign size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Ticket Médio</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">
                 {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(avgTicket)}
              </h3>
            </div>
            <div className="p-2 bg-gray-50 rounded-lg text-gray-400">
              <Target size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Taxa Conversão</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">{conversionRate.toFixed(1)}%</h3>
            </div>
            <div className="p-2 bg-purple-50 rounded-lg text-purple-600">
              <TrendingUp size={20} />
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
        {/* Funnel Chart */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-bold text-gray-900 mb-4">Status do Funil</h3>
          <div className="h-64 flex items-center justify-center relative">
             <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={funnelData}
                    innerRadius={60}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {funnelData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute text-center">
                <span className="block text-2xl font-bold text-gray-800">{totalLeads}</span>
                <span className="text-xs text-gray-500 uppercase">Leads</span>
              </div>
          </div>
          <div className="flex flex-wrap justify-center gap-3 mt-2">
              {funnelData.map((d) => (
                <div key={d.name} className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: d.color }}></div>
                  <span className="text-xs text-gray-600">{d.name}</span>
                </div>
              ))}
            </div>
        </div>

        {/* AI Analysis Section */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 lg:col-span-2 flex flex-col">
          <div className="flex justify-between items-center mb-6">
            <div className="flex items-center gap-2 text-purple-700">
              <div className="p-1.5 bg-purple-100 rounded-lg">
                <Sparkles size={18} />
              </div>
              <h3 className="text-lg font-bold">Análise de Qualidade de Leads</h3>
            </div>
            {!aiAnalysis && (
              <button 
                onClick={handleAnalyzeLeads}
                disabled={isAnalyzing || totalLeads === 0}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium flex items-center gap-2 transition-all"
              >
                {isAnalyzing ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
                {isAnalyzing ? 'Analisando...' : 'Gerar Relatório com IA'}
              </button>
            )}
          </div>

          <div className="flex-1 bg-purple-50/50 rounded-xl p-6 border border-purple-100 overflow-y-auto max-h-[300px]">
            {aiAnalysis ? (
              <div className="prose prose-sm prose-purple max-w-none">
                <ReactMarkdown>{aiAnalysis}</ReactMarkdown>
                <div className="mt-4 flex justify-end">
                   <button onClick={() => setAiAnalysis(null)} className="text-xs text-purple-600 hover:underline">Regerar análise</button>
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center text-gray-500">
                <Filter size={32} className="mb-2 text-gray-300" />
                <p>Clique no botão para analisar o perfil e valor dos leads captados.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Leads Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <div className="px-6 py-4 border-b border-gray-100">
          <h3 className="font-bold text-gray-900">Leads Captados ({totalLeads})</h3>
        </div>
        <table className="w-full text-left">
          <thead className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
            <tr>
              <th className="px-6 py-3 font-medium">Nome</th>
              <th className="px-6 py-3 font-medium">Email</th>
              <th className="px-6 py-3 font-medium">Status</th>
              <th className="px-6 py-3 font-medium">Valor Oportunidade</th>
              <th className="px-6 py-3 font-medium">Data</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {formLeads.map((lead) => (
              <tr 
                key={lead.id} 
                onClick={() => setSelectedLead(lead)}
                className="hover:bg-gray-50 transition-colors cursor-pointer group"
              >
                <td className="px-6 py-4">
                  <span className="font-medium text-gray-900 group-hover:text-primary-600 transition-colors">{lead.name}</span>
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  {lead.email}
                </td>
                <td className="px-6 py-4">
                  <span className={`text-xs px-2 py-1 rounded-full font-medium ${
                     lead.status === 'Novo' ? 'bg-blue-100 text-blue-700' :
                     lead.status === 'Vendido' ? 'bg-green-100 text-green-700' :
                     lead.status === 'Perdido' ? 'bg-red-100 text-red-700' :
                     'bg-yellow-100 text-yellow-700'
                  }`}>
                    {lead.status}
                  </span>
                </td>
                <td className="px-6 py-4 font-medium text-gray-700">
                  {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(lead.value)}
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  <div className="flex items-center gap-1">
                    <Calendar size={14} />
                    {new Date(lead.date || Date.now()).toLocaleDateString('pt-BR')}
                  </div>
                </td>
              </tr>
            ))}
            {formLeads.length === 0 && (
              <tr>
                <td colSpan={5} className="px-6 py-12 text-center text-gray-500">
                  Nenhum lead captado por este formulário ainda.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Lead Details Panel */}
      {selectedLead && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30">
          {/* Full Screen Panel */}
          <div className="w-full h-full bg-white shadow-2xl flex flex-col animate-in fade-in duration-300">
            <div className="p-4 border-b border-gray-100 flex justify-between items-start bg-gray-50 sticky top-0 z-10">
              <div>
                <h2 className="text-lg font-bold text-gray-900">{selectedLead.name}</h2>
                <div className="flex items-center gap-2 mt-2">
                  <span className={`px-3 py-1 rounded-full text-sm font-bold ${
                     selectedLead.status === 'Novo' ? 'bg-blue-100 text-blue-700' :
                     selectedLead.status === 'Vendido' ? 'bg-green-100 text-green-700' :
                     selectedLead.status === 'Perdido' ? 'bg-red-100 text-red-700' :
                     'bg-yellow-100 text-yellow-700'
                  }`}>
                    {selectedLead.status}
                  </span>
                  <span className="text-sm text-gray-500">
                    {new Date(selectedLead.date || Date.now()).toLocaleDateString('pt-BR', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                  </span>
                </div>
              </div>
              <button onClick={() => setSelectedLead(null)} className="text-gray-400 hover:text-gray-600 bg-white rounded-full p-2 hover:bg-gray-200 transition-colors">
                <X size={20} />
              </button>
            </div>

            <div className="p-6 overflow-y-auto flex-1">
              <div className="max-w-4xl mx-auto space-y-6">
              {/* Contact Info */}
              <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-xl border border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="bg-white p-2 rounded-lg text-gray-500"><Mail size={18} /></div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase font-semibold">Email</p>
                    <p className="text-sm text-gray-800">{selectedLead.email || 'Não informado'}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <div className="bg-white p-2 rounded-lg text-green-600"><DollarSign size={18} /></div>
                  <div>
                    <p className="text-xs text-gray-500 uppercase font-semibold">Valor Oportunidade</p>
                    <p className="text-sm font-bold text-green-700">
                      {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(selectedLead.value)}
                    </p>
                  </div>
                </div>
              </div>

              {/* Form Answers */}
              {selectedLead.answers && Object.keys(selectedLead.answers).length > 0 && (
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <FileText size={18} className="text-gray-400" />
                    <h3 className="text-sm font-bold text-gray-900 uppercase">Respostas do Formulário</h3>
                  </div>
                  <div className="space-y-3">
                    {Object.entries(selectedLead.answers).map(([questionId, answerData]: [string, any]) => (
                      <div key={questionId} className="border border-gray-200 rounded-lg p-4 bg-white">
                        <p className="text-xs text-gray-500 font-semibold mb-1.5">{getQuestionText(questionId)}</p>
                        <div className="flex justify-between items-start">
                          <p className="text-gray-900 font-medium text-lg">{Array.isArray(answerData.value) ? answerData.value.join(', ') : answerData.value}</p>
                          {answerData.optionSelected?.value > 0 && (
                            <span className="text-xs font-bold text-green-600 bg-green-50 px-2 py-1 rounded border border-green-100">
                              + R$ {answerData.optionSelected.value}
                            </span>
                          )}
                        </div>
                        {answerData.followUps && Object.values(answerData.followUps).some(text => text) && (
                          <div className="mt-2 pt-2 border-t border-gray-100">
                            {Object.entries(answerData.followUps).map(([optId, text]) => 
                              text ? (
                                <div key={optId}>
                                  <p className="text-xs text-gray-500 font-medium italic">Informação adicional:</p>
                                  <p className="text-gray-800 font-medium pl-2 border-l-2 border-gray-200 mt-1">{text as string}</p>
                                </div>
                              ) : null
                            )}
                          </div>
                        )}
                        {answerData.optionSelected?.script && (
                          <div className="mt-2 pt-2 border-t border-gray-100">
                            <p className="text-xs text-purple-600 font-medium italic flex items-center gap-1">
                              <Sparkles size={12} /> Dica de Venda: "{answerData.optionSelected.script}"
                            </p>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
              
              {!selectedLead.answers && (
                <div className="text-center py-8 text-gray-400 bg-gray-50 rounded-xl border border-dashed border-gray-200">
                  <p>Detalhes das respostas não disponíveis para este lead antigo.</p>
                </div>
              )}
              </div>
            </div>

            <div className="p-4 bg-gray-50 border-t border-gray-100 text-right flex-shrink-0">
              <button 
                onClick={() => setSelectedLead(null)}
                className="px-4 py-2 bg-white border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-100 font-medium"
              >
                Fechar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FormReport;
