import React, { useState, useMemo, useEffect, useRef } from 'react';
import { useTenantId } from '@/hooks/useTenantId';
import { Form, Lead } from '@/types';
import { ArrowLeft, ArrowRight, Users, DollarSign, TrendingUp, MessageSquare, Sparkles, Loader2, Download, Calendar, Target, Filter, X, Mail, Phone, FileText, Edit2, Plus, Trash2, Check, AlertCircle, Zap, Send, RefreshCw, Gift, ChevronUp, ChevronDown, ChevronsUpDown } from 'lucide-react';
import { SupabaseClient } from '@supabase/supabase-js';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import { callGeminiAPI, parseGeminiJSON } from '@/lib/gemini-client';
import Markdown from 'react-markdown';

interface Product {
  id: string;
  name: string;
  value: number;
}

interface FormReportProps {
  formId: string;
  forms: Form[];
  leads: Lead[];
  onBack: () => void;
  supabase?: SupabaseClient;
  userId?: string;
  onLeadUpdate?: (leadId: string, updatedData: any) => void;
  onLeadDelete?: (leadId: string) => void;
}

const FormReport: React.FC<FormReportProps> = ({ formId, forms, leads, onBack, supabase, userId, onLeadUpdate, onLeadDelete }) => {
  const tenantId = useTenantId()

  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState<string | null>(null);
  
  // Estados para edição de produtos recomendados
  const [products, setProducts] = useState<Product[]>([]);
  const [isEditingProducts, setIsEditingProducts] = useState(false);
  const [editedProducts, setEditedProducts] = useState<{id: string; name: string; value: number}[]>([]);
  const [wasManuallyEdited, setWasManuallyEdited] = useState(false);
  const [isSavingProducts, setIsSavingProducts] = useState(false);
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  
  // Estados para o layout de duas colunas
  const [detailSection, setDetailSection] = useState<'products' | 'ai' | 'answers' | 'notes' | null>('products');

  // Estados para anotações de negociação
  const [negotiationNoteText, setNegotiationNoteText] = useState('');
  const [isSavingNegotiationNote, setIsSavingNegotiationNote] = useState(false);

  // Estado para edição de valor individual de produto
  const [editingProductValueId, setEditingProductValueId] = useState<string | null>(null);
  const [editingProductValueText, setEditingProductValueText] = useState('');
  
  // Estados para o chat com IA
  const [chatMessages, setChatMessages] = useState<{role: 'user' | 'ai'; content: string}[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [isChatLoading, setIsChatLoading] = useState(false);
  const chatEndRef = useRef<HTMLDivElement>(null);
  const [isReanalyzing, setIsReanalyzing] = useState(false);
  const [pendingUpdate, setPendingUpdate] = useState<any>(null);

  // Filter & Sort State
  const [dateFrom, setDateFrom] = useState<string>('');
  const [dateTo, setDateTo] = useState<string>('');
  const [sortColumn, setSortColumn] = useState<'name' | 'email' | 'status' | 'value' | 'date' | null>('date');
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');

  // 1. Get Form Data
  const form = forms.find(f => f.id === formId);
  
  // 2. Filter Leads generated by this Form
  const formLeads = useMemo(() => {
    if (!form) return [];
    return leads.filter(l => {
        // Strict match by ID if available, otherwise loose match by name (legacy)
        if (l.formId && form.id) {
            return l.formId === form.id;
        }
        return l.formSource === form.name;
    });
  }, [form, leads]);

  // Filtro e ordenação
  const filteredAndSorted = useMemo(() => {
    let data = [...formLeads];
    if (dateFrom) {
      const from = new Date(dateFrom + 'T00:00:00');
      data = data.filter(l => new Date(l.date || 0) >= from);
    }
    if (dateTo) {
      const to = new Date(dateTo + 'T23:59:59');
      data = data.filter(l => new Date(l.date || 0) <= to);
    }
    if (sortColumn) {
      data.sort((a, b) => {
        let valA: string | number = '';
        let valB: string | number = '';
        if (sortColumn === 'name') { valA = a.name?.toLowerCase() || ''; valB = b.name?.toLowerCase() || ''; }
        if (sortColumn === 'email') { valA = a.email?.toLowerCase() || ''; valB = b.email?.toLowerCase() || ''; }
        if (sortColumn === 'status') { valA = a.status || ''; valB = b.status || ''; }
        if (sortColumn === 'value') { valA = a.value || 0; valB = b.value || 0; }
        if (sortColumn === 'date') { valA = new Date(a.date || 0).getTime(); valB = new Date(b.date || 0).getTime(); }
        if (valA < valB) return sortDirection === 'asc' ? -1 : 1;
        if (valA > valB) return sortDirection === 'asc' ? 1 : -1;
        return 0;
      });
    }
    return data;
  }, [formLeads, dateFrom, dateTo, sortColumn, sortDirection]);

  const handleSort = (col: 'name' | 'email' | 'status' | 'value' | 'date') => {
    if (sortColumn === col) setSortDirection(d => d === 'asc' ? 'desc' : 'asc');
    else { setSortColumn(col); setSortDirection('asc'); }
  };

  const SortIcon = ({ col }: { col: 'name' | 'email' | 'status' | 'value' | 'date' }) => {
    if (sortColumn !== col) return <ChevronsUpDown size={12} className="ml-1 text-gray-300" />;
    return sortDirection === 'asc'
      ? <ChevronUp size={12} className="ml-1 text-primary-500" />
      : <ChevronDown size={12} className="ml-1 text-primary-500" />;
  };

  // 3. Calculate Metrics
  const totalLeads = formLeads.length;
  const totalValue = formLeads.reduce((acc, curr) => acc + curr.value, 0);
  const avgTicket = totalLeads > 0 ? totalValue / totalLeads : 0;
  
  const leadsSold = formLeads.filter(l => l.status === 'Vendido').length;
  const conversionRate = totalLeads > 0 ? (leadsSold / totalLeads) * 100 : 0;

  // Status Distribution Data
  const statusCounts = formLeads.reduce((acc, lead) => {
    acc[lead.status] = (acc[lead.status] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const funnelData = [
    { name: 'Novo', value: statusCounts['Novo'] || 0, color: '#6ee7b7' },
    { name: 'Em Contato', value: statusCounts['Em Contato'] || 0, color: '#34d399' },
    { name: 'Negoc.', value: statusCounts['Negociação'] || 0, color: '#10b981' },
    { name: 'Vendido', value: statusCounts['Vendido'] || 0, color: '#059669' },
    { name: 'Perdido', value: statusCounts['Perdido'] || 0, color: '#ef4444' },
  ].filter(d => d.value > 0);

  // Carregar produtos disponíveis
  useEffect(() => {
    const fetchProducts = async () => {
      if (!supabase || !userId) {
        console.log('FormReport: supabase ou userId não disponível', { supabase: !!supabase, userId });
        return;
      }
      try {
        console.log('FormReport: Carregando produtos para userId:', userId);
        const { data, error } = await supabase
          .from('products_services')
          .select('id, name, value')
          .eq('tenant_id', tenantId);
        
        if (error) {
          console.error('FormReport: Erro ao carregar produtos:', error);
          return;
        }
        
        if (data) {
          console.log('FormReport: Produtos carregados:', data.length, data);
          setProducts(data);
        }
      } catch (err) {
        console.error('FormReport: Exceção ao carregar produtos:', err);
      }
    };
    fetchProducts();
  }, [supabase, userId]);

  const handleDeleteLead = async (leadId: string) => {
    if (!window.confirm('Tem certeza que deseja excluir este lead? Esta ação não pode ser desfeita.')) return;
    if (!supabase) return;
    
    const { error } = await supabase.from('leads').delete().eq('id', leadId);
    
    if (error) {
      console.error('Erro ao deletar lead:', error);
      alert('Erro ao excluir lead. Tente novamente.');
      return;
    }
    
    if (onLeadDelete) onLeadDelete(leadId);
    if (selectedLead?.id === leadId) setSelectedLead(null);
  };

  // Inicializar produtos editados quando seleciona um lead
  useEffect(() => {
    if (selectedLead?.answers?._ai_analysis) {
      const analysis = selectedLead.answers._ai_analysis;
      // Verificar se já foi editado manualmente
      setWasManuallyEdited(analysis.manually_edited || false);
      // Carregar produtos recomendados (pode ser um ou múltiplos)
      if (analysis.recommended_products && Array.isArray(analysis.recommended_products)) {
        setEditedProducts(analysis.recommended_products);
      } else if (analysis.suggested_product) {
        setEditedProducts([{
          id: 'original',
          name: analysis.suggested_product,
          value: analysis.suggested_value || 0
        }]);
      } else {
        setEditedProducts([]);
      }
    }
  }, [selectedLead]);

  // Reset estados ao selecionar novo lead
  useEffect(() => {
    if (selectedLead) {
      setDetailSection('products');
      setChatMessages([]);
      setChatInput('');
      setIsEditingProducts(false);
    }
  }, [selectedLead?.id]);

  // Scroll automático do chat
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [chatMessages]);

  // Funções de edição de produtos
  const handleAddProduct = (product: Product) => {
    if (!editedProducts.find(p => p.id === product.id)) {
      setEditedProducts([...editedProducts, { id: product.id, name: product.name, value: product.value }]);
    }
  };

  const handleRemoveProduct = (productId: string) => {
    setEditedProducts(editedProducts.filter(p => p.id !== productId));
  };

  // Salvar anotação de negociação
  const handleSaveNegotiationNote = async () => {
    if (!selectedLead || !supabase || !negotiationNoteText.trim()) return;
    setIsSavingNegotiationNote(true);
    try {
      const existing = selectedLead.negotiation_notes || '';
      const timestamp = new Date().toLocaleString('pt-BR');
      const newEntry = `[${timestamp}]\n${negotiationNoteText.trim()}`;
      const updated = existing ? `${existing}\n\n---\n\n${newEntry}` : newEntry;
      const { error } = await supabase
        .from('leads')
        .update({ negotiation_notes: updated })
        .eq('id', selectedLead.id);
      if (!error) {
        setNegotiationNoteText('');
        const updatedLead = { ...selectedLead, negotiation_notes: updated };
        setSelectedLead(updatedLead);
        if (onLeadUpdate) onLeadUpdate(selectedLead.id, { negotiation_notes: updated });
      }
    } catch (err) {
      console.error('Erro ao salvar anotação:', err);
    } finally {
      setIsSavingNegotiationNote(false);
    }
  };

  // Atualizar valor de produto individualmente
  const handleUpdateProductValue = (productId: string, newValue: number) => {
    setEditedProducts(prev => prev.map(p => p.id === productId ? { ...p, value: newValue } : p));
    setEditingProductValueId(null);
  };

  const handleSaveProductEdits = async () => {
    if (!selectedLead || !supabase) return;
    setIsSavingProducts(true);
    try {
      const totalValue = editedProducts.reduce((sum, p) => sum + p.value, 0);
      const updatedAnalysis = {
        ...selectedLead.answers?._ai_analysis,
        recommended_products: editedProducts,
        suggested_product: editedProducts.map(p => p.name).join(', '),
        suggested_value: totalValue,
        manually_edited: true,
        edited_at: new Date().toISOString()
      };

      const updatedAnswers = {
        ...selectedLead.answers,
        _ai_analysis: updatedAnalysis
      };

      const { error } = await supabase
        .from('leads')
        .update({ answers: updatedAnswers, value: totalValue })
        .eq('id', selectedLead.id);

      if (!error) {
        setWasManuallyEdited(true);
        setIsEditingProducts(false);
        // Atualizar lead local
        if (onLeadUpdate) {
          onLeadUpdate(selectedLead.id, { answers: updatedAnswers, value: totalValue });
        }
        // Atualizar selectedLead
        setSelectedLead({
          ...selectedLead,
          answers: updatedAnswers,
          value: totalValue
        });
      }
    } catch (err) {
      console.error('Erro ao salvar edições:', err);
    } finally {
      setIsSavingProducts(false);
    }
  };

  // Função de reanálise com IA baseada nos produtos editados
  const handleReanalyzeWithAI = async () => {
    if (!selectedLead || !supabase) return;
    setIsReanalyzing(true);
    try {
      // Chamada via proxy server-side com retry

      const answersText = selectedLead.answers 
        ? Object.entries(selectedLead.answers)
            .filter(([k]) => !k.startsWith('_'))
            .map(([qId, a]: [string, any]) => `${getQuestionText(qId)}: ${Array.isArray(a.value) ? a.value.join(', ') : a.value}`)
            .join('\n')
        : 'Sem respostas';

      const productsText = editedProducts.map(p => `${p.name} (R$ ${p.value})`).join(', ');

      const prompt = `Você é um consultor de vendas especialista. Refaça a análise deste lead considerando os produtos/serviços ATUALIZADOS.

CLIENTE: ${selectedLead.name}
PRODUTOS/SERVIÇOS SELECIONADOS: ${productsText}
VALOR TOTAL: R$ ${editedProducts.reduce((s, p) => s + p.value, 0)}

RESPOSTAS DO FORMULÁRIO:
${answersText}

Retorne APENAS um JSON válido (sem markdown) com:
{
  "classification": "opportunity" ou "risk" ou "monitoring",
  "confidence": 0.0 a 1.0,
  "reasoning": "explicação detalhada",
  "client_insights": ["insight1", "insight2"],
  "next_steps": ["passo1", "passo2"],
  "sales_script": "script de abordagem personalizado"
}`;

      const aiText = await callGeminiAPI(prompt);
      const analysis = parseGeminiJSON(aiText);

      const updatedAnalysis = {
        ...selectedLead.answers?._ai_analysis,
        ...analysis,
        recommended_products: editedProducts,
        suggested_product: editedProducts.map(p => p.name).join(', '),
        suggested_value: editedProducts.reduce((s, p) => s + p.value, 0),
        manually_edited: true,
        reanalyzed_at: new Date().toISOString()
      };

      const updatedAnswers = { ...selectedLead.answers, _ai_analysis: updatedAnalysis };
      const totalValue = editedProducts.reduce((s, p) => s + p.value, 0);

      await supabase.from('leads').update({ answers: updatedAnswers, value: totalValue }).eq('id', selectedLead.id);
      if (onLeadUpdate) onLeadUpdate(selectedLead.id, { answers: updatedAnswers, value: totalValue });
      setSelectedLead({ ...selectedLead, answers: updatedAnswers, value: totalValue });
      setChatMessages(prev => [...prev, { role: 'ai', content: '✅ Análise atualizada com sucesso com os novos produtos/serviços!' }]);
    } catch (err) {
      console.error('Erro na reanálise:', err);
      setChatMessages(prev => [...prev, { role: 'ai', content: '❌ Erro ao refazer a análise. Tente novamente.' }]);
    } finally {
      setIsReanalyzing(false);
    }
  };

  // Função para aplicar atualização pendente (inclui produtos)
  const handleApplyPendingUpdate = async () => {
    if (!pendingUpdate || !selectedLead || !supabase) return;
    setIsChatLoading(true);
    try {
      const currentAnalysis = selectedLead.answers?._ai_analysis;
      // Atualizar os produtos se a IA indicou novos produtos
      let newProducts = editedProducts;
      if (pendingUpdate.new_products && Array.isArray(pendingUpdate.new_products)) {
        newProducts = pendingUpdate.new_products;
        setEditedProducts(newProducts);
        setIsEditingProducts(false);
      }
      const { new_products, ...analysisFields } = pendingUpdate;
      const updatedAnalysis = {
        ...currentAnalysis,
        ...analysisFields,
        recommended_products: newProducts,
        suggested_product: newProducts.map((p: any) => p.name).join(', '),
        suggested_value: newProducts.reduce((s: number, p: any) => s + p.value, 0),
        chat_updated_at: new Date().toISOString()
      };
      const updatedAnswers = { ...selectedLead.answers, _ai_analysis: updatedAnalysis };
      const newValue = newProducts.reduce((s: number, p: any) => s + p.value, 0);
      await supabase.from('leads').update({ answers: updatedAnswers, value: newValue }).eq('id', selectedLead.id);
      if (onLeadUpdate) onLeadUpdate(selectedLead.id, { answers: updatedAnswers, value: newValue });
      setSelectedLead({ ...selectedLead, answers: updatedAnswers, value: newValue });
      setChatMessages(prev => [...prev, { role: 'ai', content: 'Pronto! Produtos e análise atualizados com sucesso.' }]);
      setPendingUpdate(null);
    } catch (err) {
      console.error('Erro ao aplicar:', err);
      setChatMessages(prev => [...prev, { role: 'ai', content: 'Erro ao salvar. Tente novamente.' }]);
    } finally {
      setIsChatLoading(false);
    }
  };

  const handleRejectPendingUpdate = () => {
    setPendingUpdate(null);
    setChatMessages(prev => [...prev, { role: 'ai', content: 'Ok, descartei a alteração. O que gostaria de ajustar?' }]);
  };

  // Função de chat com IA
  const handleChatSend = async () => {
    if (!chatInput.trim() || !selectedLead || isChatLoading) return;
    const userMessage = chatInput.trim();
    setChatInput('');
    setChatMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setIsChatLoading(true);

    try {
      // Chamada via proxy server-side com retry

      const currentAnalysis = selectedLead.answers?._ai_analysis;
      const answersText = selectedLead.answers 
        ? Object.entries(selectedLead.answers)
            .filter(([k]) => !k.startsWith('_'))
            .map(([qId, a]: [string, any]) => `${getQuestionText(qId)}: ${Array.isArray(a.value) ? a.value.join(', ') : a.value}`)
            .join('\n')
        : '';

      const productsAvailable = products.map(p => `${p.name}: R$ ${p.value}`).join('\n');
      const productsSelected = editedProducts.map(p => `${p.name}: R$ ${p.value}`).join('\n');
      const chatHistory = chatMessages.slice(-10).map(m => `${m.role === 'user' ? 'Usuário' : 'IA'}: ${m.content}`).join('\n');

      const prompt = `Você é um consultor de vendas do sistema HelloGrowth.

REGRAS OBRIGATÓRIAS:
1. SEMPRE responda em português do Brasil, respostas CURTAS (máximo 3 frases)
2. NUNCA retorne JSON, código, markdown ou texto técnico ao usuário
3. NUNCA use palavras em inglês
4. Seja fiel às respostas do cliente - respeite orçamento e preferências
5. SEMPRE QUESTIONE antes de alterar. Explique o impacto da mudança
6. Só confirme quando o usuário disser "sim", "confirma", "pode fazer", "faz isso", "isso"

PRODUTOS ATUALMENTE SELECIONADOS PARA ESTE CLIENTE:
${productsSelected || 'Nenhum'}

TODOS OS PRODUTOS/SERVIÇOS DISPONÍVEIS NA EMPRESA:
${productsAvailable}

RESPOSTAS DO CLIENTE NO FORMULÁRIO:
${answersText}

ANÁLISE ATUAL:
Classificação: ${currentAnalysis?.classification || 'N/A'}
Confiança: ${currentAnalysis?.confidence ? Math.round(currentAnalysis.confidence * 100) + '%' : 'N/A'}
Raciocínio: ${currentAnalysis?.reasoning || 'N/A'}

HISTÓRICO DA CONVERSA:
${chatHistory}

MENSAGEM DO USUÁRIO: ${userMessage}

INSTRUÇÕES DE RESPOSTA:
- Se o usuário está apenas perguntando ou conversando: responda em texto curto e simples
- Se o usuário está CONFIRMANDO uma alteração que você já questionou (disse sim, confirma, pode fazer, faz isso, isso, etc.):
  Responda EXATAMENTE neste formato técnico (será processado pelo sistema, o usuário NÃO verá isso):
  ACAO|produtos_finais|classificação|confiança|raciocínio curto
  
  Onde produtos_finais é a lista dos nomes dos produtos que devem FICAR selecionados, separados por vírgula.
  Exemplo: ACAO|Inova Diamante|opportunity|0.9|Cliente focado em atendimento premium
  Exemplo com 2 produtos: ACAO|Inova Diamante,Avaliação física|opportunity|0.85|Cliente quer acompanhamento completo
  
  IMPORTANTE: Inclua APENAS os produtos que devem ficar. Se o usuário pediu para remover um, NÃO inclua ele.`;

      let responseText = (await callGeminiAPI(prompt)).trim();

      // Verificar se a IA retornou uma ação de atualização
      if (responseText.startsWith('ACAO|')) {
        try {
          const parts = responseText.split('|');
          const productNames = parts[1]?.split(',').map(s => s.trim()).filter(Boolean) || [];
          
          // Encontrar os produtos reais pelo nome
          const newProducts = productNames.map(name => {
            const found = products.find(p => p.name.toLowerCase() === name.toLowerCase());
            return found ? { name: found.name, value: found.value } : null;
          }).filter(Boolean) as {name: string; value: number}[];
          
          const totalValue = newProducts.reduce((s, p) => s + p.value, 0);
          const productList = newProducts.map(p => `${p.name} (R$ ${p.value.toLocaleString('pt-BR', {minimumFractionDigits: 2})})`).join(', ');
          
          const updateData = {
            classification: parts[2]?.trim() || currentAnalysis?.classification,
            confidence: parseFloat(parts[3]) || currentAnalysis?.confidence,
            reasoning: parts[4]?.trim() || currentAnalysis?.reasoning,
            new_products: newProducts
          };
          setPendingUpdate(updateData);
          setChatMessages(prev => [...prev, { role: 'ai', content: `Vou alterar para: ${productList}. Total: R$ ${totalValue.toLocaleString('pt-BR', {minimumFractionDigits: 2})}. Confirma?` }]);
        } catch {
          setChatMessages(prev => [...prev, { role: 'ai', content: responseText }]);
        }
      } else {
        setChatMessages(prev => [...prev, { role: 'ai', content: responseText }]);
      }
    } catch (err) {
      console.error('Erro no chat:', err);
      setChatMessages(prev => [...prev, { role: 'ai', content: 'Erro ao processar. Tente novamente.' }]);
    } finally {
      setIsChatLoading(false);
    }
  };

  // 4. AI Analysis Handler
  const handleAnalyzeLeads = async () => {
    if (formLeads.length === 0) return;
    
    setIsAnalyzing(true);
    try {
        const leadsSummary = formLeads
          .map(l => `- ${l.name}: Status "${l.status}", Valor R$${l.value}`)
          .join('\n');

        // Calcular metricas detalhadas por status
        const statusBreakdown = formLeads.reduce((acc: Record<string, {count: number, value: number}>, l) => {
          const s = l.status || 'Novo';
          if (!acc[s]) acc[s] = {count: 0, value: 0};
          acc[s].count++;
          acc[s].value += Number(l.value || 0);
          return acc;
        }, {});
        const ticketMedio = formLeads.length > 0 ? (totalValue / formLeads.length).toFixed(2) : '0';
        const vendidos = formLeads.filter(l => l.status === 'Vendido');
        const ticketMedioVendidos = vendidos.length > 0 ? (vendidos.reduce((s, l) => s + l.value, 0) / vendidos.length).toFixed(2) : '0';

        const prompt = `Voce e um Gerente de Vendas e Growth com expertise em otimizacao de funis de captacao. Analise a performance do formulario "${form?.name}".

METRICAS DO FORMULARIO:
- Total de Leads: ${totalLeads}
- Valor Total em Pipeline: R$ ${totalValue}
- Taxa de Conversao: ${conversionRate.toFixed(1)}%
- Ticket Medio Geral: R$ ${ticketMedio}
- Ticket Medio Vendidos: R$ ${ticketMedioVendidos}
- Distribuicao por Status: ${Object.entries(statusBreakdown).map(([s, d]) => `${s}: ${d.count} leads (R$ ${d.value.toLocaleString('pt-BR')})`).join(', ')}

LISTA DE LEADS:
${leadsSummary.substring(0, 2000)}

Gere em Markdown:

## 1. Qualidade dos Leads
- O formulario esta trazendo leads de ALTO VALOR?
- Qual o perfil predominante dos leads captados?
- Existe padrao nos leads que convertem vs os que nao convertem?

## 2. Gargalos do Funil
- Em qual etapa os leads ficam PARADOS? (cite numeros)
- Qual a taxa de abandono entre cada etapa?
- Existe um "buraco" no funil onde se perde mais valor?

## 3. Otimizacoes Recomendadas
Para cada sugestao:
- O que mudar (no formulario ou na abordagem)
- Por que (baseado nos dados)
- Impacto esperado em conversao e receita

Seja ESPECIFICO e baseie TUDO nos dados reais.
        `;

        const text = await callGeminiAPI(prompt);
        setAiAnalysis(text || "Não foi possível gerar a análise.");
    } catch (error) {
      console.error(error);
      setAiAnalysis("Erro ao processar análise com IA.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  // Helper to resolve question text
  const getQuestionText = (questionId: string) => {
    const question = form?.questions.find(q => q.id === questionId);
    return question ? question.text : `Pergunta desconhecida (${questionId})`;
  };

  if (!form) return <div>Formulário não encontrado</div>;

  return (
    <div className="p-8 min-h-screen bg-gray-50 relative">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-gray-200 rounded-full transition-colors">
            <ArrowLeft size={24} className="text-gray-600" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
              {form.name}
              <span className={`text-xs px-2 py-1 rounded-full border ${form.active ? 'bg-green-50 text-green-700 border-green-200' : 'bg-gray-100 text-gray-600 border-gray-200'}`}>
                {form.active ? 'Ativo' : 'Inativo'}
              </span>
              {form.game_enabled && (
                <span className="text-xs px-2 py-1 rounded-full border border-purple-100 text-purple-600 bg-purple-50 flex items-center gap-1">
                  <Gift size={12} /> Game Ativo
                </span>
              )}
            </h1>
            <p className="text-gray-500 text-sm mt-1">Performance de captação e qualificação</p>
          </div>
        </div>
        <button className="flex items-center gap-2 px-4 py-2 bg-white border border-gray-200 rounded-lg text-gray-600 hover:bg-gray-50 text-sm font-medium">
          <Download size={16} /> Exportar CSV
        </button>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Total Leads</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">{totalLeads}</h3>
            </div>
            <div className="p-2 bg-blue-50 rounded-lg text-blue-600">
              <Users size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Valor em Pipeline</p>
              <h3 className="text-3xl font-bold text-green-600 mt-2">
                {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(totalValue)}
              </h3>
            </div>
            <div className="p-2 bg-green-50 rounded-lg text-green-600">
              <DollarSign size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Ticket Médio</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">
                 {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 }).format(avgTicket)}
              </h3>
            </div>
            <div className="p-2 bg-gray-50 rounded-lg text-gray-400">
              <Target size={20} />
            </div>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <p className="text-sm font-medium text-gray-500">Taxa Conversão</p>
              <h3 className="text-3xl font-bold text-gray-900 mt-2">{conversionRate.toFixed(1)}%</h3>
            </div>
            <div className="p-2 bg-purple-50 rounded-lg text-purple-600">
              <TrendingUp size={20} />
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
        {/* Funnel Chart */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <h3 className="text-lg font-bold text-gray-900 mb-4">Status do Funil</h3>
          <div className="h-64 flex items-center justify-center relative">
             <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={funnelData}
                    innerRadius={60}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {funnelData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
              <div className="absolute text-center">
                <span className="block text-2xl font-bold text-gray-800">{totalLeads}</span>
                <span className="text-xs text-gray-500 uppercase">Leads</span>
              </div>
          </div>
          <div className="flex flex-wrap justify-center gap-3 mt-2">
              {funnelData.map((d) => (
                <div key={d.name} className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: d.color }}></div>
                  <span className="text-xs text-gray-600">{d.name}</span>
                </div>
              ))}
            </div>
        </div>

        {/* AI Analysis Section */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 lg:col-span-2 flex flex-col">
          <div className="flex justify-between items-center mb-6">
            <div className="flex items-center gap-2 text-purple-700">
              <div className="p-1.5 bg-purple-100 rounded-lg">
                <Sparkles size={18} />
              </div>
              <h3 className="text-lg font-bold">Análise de Qualidade de Leads</h3>
            </div>
            {!aiAnalysis && (
              <button 
                onClick={handleAnalyzeLeads}
                disabled={isAnalyzing || totalLeads === 0}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-sm font-medium flex items-center gap-2 transition-all"
              >
                {isAnalyzing ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}
                {isAnalyzing ? 'Analisando...' : 'Gerar Relatório com IA'}
              </button>
            )}
          </div>

          <div className="flex-1 bg-purple-50/50 rounded-xl p-6 border border-purple-100 overflow-y-auto max-h-[300px]">
            {aiAnalysis ? (
              <div className="prose prose-sm prose-purple max-w-none">
                <Markdown>{aiAnalysis}</Markdown>
                <div className="mt-4 flex justify-end">
                   <button onClick={() => setAiAnalysis(null)} className="text-xs text-purple-600 hover:underline">Regerar análise</button>
                </div>
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-center text-gray-500">
                <Filter size={32} className="mb-2 text-gray-300" />
                <p>Clique no botão para analisar o perfil e valor dos leads captados.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Leads Table */}
      <div className="flex flex-wrap items-center justify-between gap-4 mb-4">
        <h3 className="font-bold text-gray-900">Leads Captados
          <span className="ml-2 text-sm font-normal text-gray-400">{filteredAndSorted.length} de {totalLeads}</span>
        </h3>
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2 bg-white border border-gray-200 rounded-lg px-3 py-2 shadow-sm">
            <Filter size={14} className="text-gray-400" />
            <span className="text-xs text-gray-500 font-medium">De</span>
            <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)} className="text-xs text-gray-700 border-none outline-none bg-transparent cursor-pointer" />
          </div>
          <div className="flex items-center gap-2 bg-white border border-gray-200 rounded-lg px-3 py-2 shadow-sm">
            <span className="text-xs text-gray-500 font-medium">Até</span>
            <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)} className="text-xs text-gray-700 border-none outline-none bg-transparent cursor-pointer" />
          </div>
          {(dateFrom || dateTo) && (
            <button onClick={() => { setDateFrom(''); setDateTo(''); }} className="text-xs text-red-500 hover:text-red-700 bg-red-50 hover:bg-red-100 px-3 py-2 rounded-lg transition-colors font-medium">Limpar filtro</button>
          )}
        </div>
      </div>
      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
            <tr>
              <th className="px-6 py-3 font-medium"><button onClick={() => handleSort('name')} className="flex items-center hover:text-gray-700 transition-colors">Nome <SortIcon col="name" /></button></th>
              <th className="px-6 py-3 font-medium"><button onClick={() => handleSort('email')} className="flex items-center hover:text-gray-700 transition-colors">Email <SortIcon col="email" /></button></th>
              <th className="px-6 py-3 font-medium"><button onClick={() => handleSort('status')} className="flex items-center hover:text-gray-700 transition-colors">Status <SortIcon col="status" /></button></th>
              <th className="px-6 py-3 font-medium"><button onClick={() => handleSort('value')} className="flex items-center hover:text-gray-700 transition-colors">Valor Oportunidade <SortIcon col="value" /></button></th>
              <th className="px-6 py-3 font-medium"><button onClick={() => handleSort('date')} className="flex items-center hover:text-gray-700 transition-colors">Data <SortIcon col="date" /></button></th>
              <th className="px-6 py-3 font-medium"></th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {filteredAndSorted.length === 0 ? (
              <tr><td colSpan={6} className="px-6 py-12 text-center text-gray-400 text-sm">Nenhum lead encontrado para o período selecionado.</td></tr>
            ) : filteredAndSorted.map((lead) => (
              <tr 
                key={lead.id} 
                onClick={() => setSelectedLead(lead)}
                className="hover:bg-gray-50 transition-colors cursor-pointer group"
              >
                <td className="px-6 py-4">
                  <span className="font-medium text-gray-900 group-hover:text-primary-600 transition-colors">{lead.name}</span>
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  {lead.email}
                </td>
                <td className="px-6 py-4">
                  <span className={`text-xs px-2 py-1 rounded-full font-medium ${
                     lead.status === 'Novo' ? 'bg-blue-100 text-blue-700' :
                     lead.status === 'Vendido' ? 'bg-green-100 text-green-700' :
                     lead.status === 'Perdido' ? 'bg-red-100 text-red-700' :
                     'bg-yellow-100 text-yellow-700'
                  }`}>
                    {lead.status}
                  </span>
                </td>
                <td className="px-6 py-4 font-medium text-gray-700">
                  {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(lead.value)}
                </td>
                <td className="px-6 py-4 text-sm text-gray-500">
                  <div className="flex items-center gap-1">
                    <Calendar size={14} />
                    {new Date(lead.date || Date.now()).toLocaleDateString('pt-BR')}
                  </div>
                </td>
                <td className="px-6 py-4 text-right" onClick={(e) => e.stopPropagation()}>
                  <button
                    onClick={() => handleDeleteLead(lead.id)}
                    className="p-1.5 text-gray-300 hover:text-red-500 hover:bg-red-50 rounded transition-colors opacity-0 group-hover:opacity-100"
                    title="Excluir lead"
                  >
                    <Trash2 size={14} />
                  </button>
                </td>
              </tr>
            ))}

          </tbody>
        </table>
      </div>

      {/* Lead Details Panel - Layout Duas Colunas */}
      {selectedLead && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30">
          <div className="w-full h-full bg-white shadow-2xl flex flex-col animate-in fade-in duration-300">
            {/* HEADER */}
            <div className="px-6 py-3 border-b border-gray-200 bg-white flex items-center justify-between flex-shrink-0">
              <div className="flex items-center gap-4">
                <h2 className="text-lg font-bold text-gray-900">{selectedLead.name}</h2>
                <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold ${
                  selectedLead.status === 'Novo' ? 'bg-blue-100 text-blue-700' :
                  selectedLead.status === 'Vendido' ? 'bg-green-100 text-green-700' :
                  selectedLead.status === 'Perdido' ? 'bg-red-100 text-red-700' :
                  'bg-yellow-100 text-yellow-700'
                }`}>{selectedLead.status}</span>
                {selectedLead.phone && (
                  <span className="flex items-center gap-1 text-sm text-gray-500"><Phone size={14} /> {selectedLead.phone}</span>
                )}
                {selectedLead.email && (
                  <span className="flex items-center gap-1 text-sm text-gray-500"><Mail size={14} /> {selectedLead.email}</span>
                )}
                <span className="flex items-center gap-1 text-sm text-gray-500">
                  <Calendar size={14} /> {new Date(selectedLead.date || Date.now()).toLocaleDateString('pt-BR')}
                </span>
              </div>
              <button onClick={() => setSelectedLead(null)} className="text-gray-400 hover:text-gray-600 p-2 hover:bg-gray-100 rounded-lg transition-colors">
                <X size={20} />
              </button>
            </div>

            {/* CORPO - Duas colunas */}
            <div className="flex-1 flex overflow-hidden">
              {/* COLUNA ESQUERDA - Controles */}
              <div className="w-[400px] flex-shrink-0 border-r border-gray-200 bg-white flex flex-col p-4 gap-3">
                
                {/* Valor e Produtos - Sempre visível */}
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-amber-700 font-semibold uppercase">Valor Identificado</span>
                    <span className="text-lg font-bold text-green-700">
                      {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(selectedLead.value)}
                    </span>
                  </div>
                  {selectedLead.answers?._ai_analysis && (
                    <div className="flex items-center gap-2 mt-2">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${
                        selectedLead.answers._ai_analysis.classification === 'opportunity' ? 'bg-green-100 text-green-700' :
                        selectedLead.answers._ai_analysis.classification === 'risk' ? 'bg-red-100 text-red-700' :
                        'bg-yellow-100 text-yellow-700'
                      }`}>
                        {selectedLead.answers._ai_analysis.classification === 'opportunity' ? 'Alta Oportunidade' :
                         selectedLead.answers._ai_analysis.classification === 'risk' ? 'Risco' : 'Monitorar'}
                      </span>
                      <span className="text-[10px] text-gray-500">
                        Confiança: {Math.round((selectedLead.answers._ai_analysis.confidence || 0) * 100)}%
                      </span>
                    </div>
                  )}
                </div>

                {/* Botão: Produtos/Serviços */}
                <button
                  onClick={() => setDetailSection(prev => prev === 'products' ? null : 'products')}
                  className={`w-full flex items-center justify-between p-3 rounded-lg border transition-colors ${
                    detailSection === 'products'
                      ? 'border-purple-300 bg-purple-50 text-purple-700'
                      : 'border-gray-200 bg-white hover:bg-gray-50 text-gray-700'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <DollarSign size={16} className={detailSection === 'products' ? 'text-purple-600' : 'text-gray-400'} />
                    <span className="text-xs font-bold uppercase">Produtos / Serviços</span>
                    {wasManuallyEdited && (
                      <span className="px-1.5 py-0.5 bg-amber-100 text-amber-700 text-[10px] font-medium rounded-full">Editado</span>
                    )}
                  </div>
                  <ArrowRight size={16} className="text-gray-400" />
                </button>

                {/* Botão: Análise da IA */}
                <button
                  onClick={() => setDetailSection(prev => prev === 'ai' ? null : 'ai')}
                  className={`w-full flex items-center justify-between p-3 rounded-lg border transition-colors ${
                    detailSection === 'ai'
                      ? 'border-amber-300 bg-amber-50 text-amber-700'
                      : 'border-gray-200 bg-white hover:bg-gray-50 text-gray-700'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <Zap size={16} className={detailSection === 'ai' ? 'text-amber-600' : 'text-gray-400'} />
                    <span className="text-xs font-bold uppercase">Análise da IA</span>
                  </div>
                  <ArrowRight size={16} className="text-gray-400" />
                </button>

                {/* Botão: Anotações de Negociação */}
                <button
                  onClick={() => setDetailSection(prev => prev === 'notes' ? null : 'notes')}
                  className={`w-full flex items-center justify-between p-3 rounded-lg border transition-colors ${
                    detailSection === 'notes'
                      ? 'border-green-300 bg-green-50 text-green-700'
                      : 'border-gray-200 bg-white hover:bg-gray-50 text-gray-700'
                  }`}
                >
                  <div className="flex items-center gap-2">
                    <MessageSquare size={16} className={detailSection === 'notes' ? 'text-green-600' : 'text-gray-400'} />
                    <span className="text-xs font-bold uppercase">Anotações da Negociação</span>
                    {selectedLead.negotiation_notes && (
                      <span className="px-1.5 py-0.5 bg-green-100 text-green-700 text-[10px] font-medium rounded-full">
                        {selectedLead.negotiation_notes.split('---').length}
                      </span>
                    )}
                  </div>
                  <ArrowRight size={16} className="text-gray-400" />
                </button>

                {/* Botão: Perguntas e Respostas */}
                {selectedLead.answers && Object.keys(selectedLead.answers).filter(k => !k.startsWith('_')).length > 0 && (
                  <button
                    onClick={() => setDetailSection(prev => prev === 'answers' ? null : 'answers')}
                    className={`w-full flex items-center justify-between p-3 rounded-lg border transition-colors ${
                      detailSection === 'answers'
                        ? 'border-blue-300 bg-blue-50 text-blue-700'
                        : 'border-gray-200 bg-white hover:bg-gray-50 text-gray-700'
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <FileText size={16} className={detailSection === 'answers' ? 'text-blue-600' : 'text-gray-400'} />
                      <span className="text-xs font-bold uppercase">Perguntas e Respostas</span>
                      <span className="text-xs text-gray-400">
                        ({Object.keys(selectedLead.answers).filter(k => !k.startsWith('_')).length})
                      </span>
                    </div>
                    <ArrowRight size={16} className="text-gray-400" />
                  </button>
                )}

                {/* Spacer */}
                <div className="flex-1" />

                {/* Chat com IA - Fixo na parte inferior da coluna esquerda */}
                <div className="border border-gray-200 rounded-lg bg-gray-50">
                  <div className="flex items-center gap-2 px-3 py-2 border-b border-gray-200">
                    <Sparkles size={14} className="text-purple-600" />
                    <span className="text-xs font-bold text-gray-700 uppercase">Chat com IA</span>
                  </div>
                  {/* Mensagens do chat */}
                  <div className="h-[180px] overflow-y-auto px-3 py-2 space-y-2">
                    {chatMessages.length === 0 && (
                      <p className="text-xs text-gray-400 text-center mt-4">
                        Converse com a IA sobre este lead. Peça para refazer a análise, adicionar observações, corrigir algo...
                      </p>
                    )}
                    {chatMessages.map((msg, i) => (
                      <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                        <div className={`max-w-[85%] px-3 py-2 rounded-lg text-xs leading-relaxed ${
                          msg.role === 'user'
                            ? 'bg-purple-600 text-white'
                            : 'bg-white border border-gray-200 text-gray-700'
                        }`}>
                          {msg.content}
                        </div>
                      </div>
                    ))}
                    {isChatLoading && (
                      <div className="flex justify-start">
                        <div className="bg-white border border-gray-200 px-3 py-2 rounded-lg">
                          <Loader2 size={14} className="animate-spin text-purple-600" />
                        </div>
                      </div>
                    )}
                    <div ref={chatEndRef} />
                  </div>
                  {/* Botões de confirmação ou Input do chat */}
                  {pendingUpdate ? (
                    <div className="px-3 py-2 border-t border-gray-200 flex gap-2">
                      <button
                        onClick={handleRejectPendingUpdate}
                        className="flex-1 px-3 py-2 text-xs font-medium border border-gray-300 text-gray-600 rounded-lg hover:bg-gray-100 transition-colors"
                      >
                        Cancelar
                      </button>
                      <button
                        onClick={handleApplyPendingUpdate}
                        disabled={isChatLoading}
                        className="flex-1 px-3 py-2 text-xs font-medium bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50 transition-colors flex items-center justify-center gap-1"
                      >
                        {isChatLoading ? <Loader2 size={12} className="animate-spin" /> : <Check size={12} />}
                        Confirmar Alteração
                      </button>
                    </div>
                  ) : (
                    <div className="px-3 py-2 border-t border-gray-200 flex gap-2">
                      <input
                        type="text"
                        value={chatInput}
                        onChange={(e) => setChatInput(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && handleChatSend()}
                        placeholder="Ex: Inclua o Inova Ouro na análise..."
                        className="flex-1 text-xs px-3 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-purple-400"
                        disabled={isChatLoading}
                      />
                      <button
                        onClick={handleChatSend}
                        disabled={!chatInput.trim() || isChatLoading}
                        className="px-3 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
                      >
                        <Send size={14} />
                      </button>
                    </div>
                  )}
                </div>

                {/* Botões de ação */}
                <div className="flex gap-2">
                  <button
                    onClick={() => {
                      const lead = selectedLead;
                      setSelectedLead(null);
                    }}
                    className="flex-1 px-3 py-2 text-sm border border-gray-200 text-gray-600 rounded-lg hover:bg-gray-50 font-medium transition-colors"
                  >
                    Fechar
                  </button>
                </div>
              </div>

              {/* COLUNA DIREITA - Conteúdo dinâmico */}
              <div className="flex-1 bg-gray-50 p-6 overflow-y-auto">
                
                {/* Conteúdo: Produtos/Serviços */}
                {detailSection === 'products' && (
                  <div>
                    <div className="flex items-center justify-between mb-4">
                      <div className="flex items-center gap-2">
                        <DollarSign size={18} className="text-purple-600" />
                        <h3 className="font-bold text-gray-900">Produtos / Serviços Recomendados</h3>
                      </div>
                      <div className="flex items-center gap-2">
                        {!isEditingProducts ? (
                          <button
                            onClick={() => setIsEditingProducts(true)}
                            className="flex items-center gap-1 px-3 py-1.5 text-purple-600 hover:bg-purple-50 rounded-lg text-sm font-medium border border-purple-200 transition-colors"
                          >
                            <Edit2 size={14} /> Editar
                          </button>
                        ) : (
                          <>
                            <button
                              onClick={() => {
                                setIsEditingProducts(false);
                                if (selectedLead?.answers?._ai_analysis?.recommended_products) {
                                  setEditedProducts(selectedLead.answers._ai_analysis.recommended_products);
                                }
                              }}
                              className="px-3 py-1.5 text-gray-600 hover:bg-gray-100 rounded-lg text-sm font-medium transition-colors"
                            >
                              Cancelar
                            </button>
                            <button
                              onClick={handleSaveProductEdits}
                              disabled={isSavingProducts}
                              className="flex items-center gap-1 px-3 py-1.5 bg-purple-600 text-white hover:bg-purple-700 rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
                            >
                              {isSavingProducts ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />}
                              Salvar
                            </button>
                          </>
                        )}
                        <button
                          onClick={handleReanalyzeWithAI}
                          disabled={isReanalyzing}
                          className="flex items-center gap-1 px-3 py-1.5 bg-amber-500 text-white hover:bg-amber-600 rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
                        >
                          {isReanalyzing ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
                          Reanalisar com IA
                        </button>
                      </div>
                    </div>

                    {/* Modo Visualização */}
                    {!isEditingProducts && (
                      <div className="space-y-3">
                        {editedProducts.length > 0 ? editedProducts.map((product, i) => (
                          <div key={i} className="bg-white rounded-lg border border-gray-200 p-4 flex justify-between items-center">
                            <div>
                              <p className="font-medium text-gray-900">{product.name}</p>
                            </div>
                            <p className="text-lg font-bold text-green-600">
                              {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(product.value)}
                            </p>
                          </div>
                        )) : (
                          <div className="bg-white rounded-lg border border-gray-200 p-4">
                            <p className="font-medium text-gray-900">{selectedLead.answers?._ai_analysis?.suggested_product || 'Nenhum produto'}</p>
                            <p className="text-lg font-bold text-green-600 mt-1">
                              {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(selectedLead.answers?._ai_analysis?.suggested_value || 0)}
                            </p>
                          </div>
                        )}
                        <div className="bg-purple-50 rounded-lg border border-purple-200 p-4 flex justify-between items-center">
                          <span className="font-semibold text-purple-700">Total</span>
                          <span className="text-xl font-bold text-green-700">
                            {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(
                              editedProducts.length > 0 ? editedProducts.reduce((s, p) => s + p.value, 0) : (selectedLead.answers?._ai_analysis?.suggested_value || 0)
                            )}
                          </span>
                        </div>
                      </div>
                    )}

                    {/* Modo Edição */}
                    {isEditingProducts && (
                      <div className="space-y-4">
                        <div>
                          <p className="text-sm font-medium text-gray-700 mb-2">Produtos selecionados:</p>
                          {editedProducts.length === 0 ? (
                            <p className="text-sm text-gray-400 italic">Nenhum produto selecionado</p>
                          ) : (
                            <div className="space-y-2">
                              {editedProducts.map((product) => (
                                <div key={product.id} className="flex items-center justify-between bg-white p-3 rounded-lg border border-purple-200">
                                  <div className="flex-1 min-w-0 mr-2">
                                    <p className="font-medium text-gray-900 text-sm truncate">{product.name}</p>
                                    {editingProductValueId === product.id ? (
                                      <div className="flex items-center gap-1 mt-1">
                                        <span className="text-xs text-gray-500">R$</span>
                                        <input
                                          autoFocus
                                          type="number"
                                          defaultValue={product.value}
                                          onBlur={e => handleUpdateProductValue(product.id, parseFloat(e.target.value) || 0)}
                                          onKeyDown={e => {
                                            if (e.key === 'Enter') handleUpdateProductValue(product.id, parseFloat((e.target as HTMLInputElement).value) || 0);
                                            if (e.key === 'Escape') setEditingProductValueId(null);
                                          }}
                                          className="w-24 text-sm border border-purple-300 rounded px-2 py-0.5 focus:outline-none focus:ring-1 focus:ring-purple-400"
                                        />
                                      </div>
                                    ) : (
                                      <button
                                        onClick={() => { setEditingProductValueId(product.id); setEditingProductValueText(String(product.value)); }}
                                        className="text-sm text-green-600 font-bold hover:text-green-800 hover:underline flex items-center gap-1 mt-0.5"
                                      >
                                        {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(product.value)}
                                        <Edit2 size={10} className="opacity-50" />
                                      </button>
                                    )}
                                  </div>
                                  <button onClick={() => handleRemoveProduct(product.id)} className="p-2 text-red-500 hover:bg-red-50 rounded-lg transition-colors flex-shrink-0">
                                    <Trash2 size={16} />
                                  </button>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                        <div>
                          <p className="text-sm font-medium text-gray-700 mb-2">Adicionar produto:</p>
                          {products.length === 0 ? (
                            <p className="text-sm text-gray-400 italic">Nenhum produto cadastrado. Cadastre em "Produtos e Serviços".</p>
                          ) : (
                            <div className="grid grid-cols-2 gap-2">
                              {products.filter(p => !editedProducts.find(ep => ep.id === p.id)).map((product) => (
                                <button
                                  key={product.id}
                                  onClick={() => handleAddProduct(product)}
                                  className="flex items-center gap-2 p-3 text-left border border-gray-200 rounded-lg hover:border-purple-300 hover:bg-purple-50 transition-colors"
                                >
                                  <Plus size={14} className="text-purple-500 flex-shrink-0" />
                                  <div className="min-w-0">
                                    <p className="text-sm font-medium text-gray-900 truncate">{product.name}</p>
                                    <p className="text-xs text-green-600">
                                      {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(product.value)}
                                    </p>
                                  </div>
                                </button>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="pt-3 border-t border-gray-200">
                          <div className="flex justify-between items-center">
                            <span className="text-sm font-medium text-gray-700">Valor Total:</span>
                            <span className="text-xl font-bold text-green-600">
                              {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(
                                editedProducts.reduce((sum, p) => sum + p.value, 0)
                              )}
                            </span>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {/* Conteúdo: Análise da IA */}
                {detailSection === 'ai' && (
                  <div>
                    <div className="flex items-center gap-2 mb-4">
                      <Zap size={18} className="text-amber-600" />
                      <h3 className="font-bold text-gray-900">Análise da IA</h3>
                    </div>
                    {selectedLead.answers?._ai_analysis ? (
                      <div className="space-y-4">
                        {selectedLead.answers._ai_analysis.reasoning && (
                          <div className="bg-white rounded-lg border border-gray-200 p-4">
                            <span className="text-xs text-gray-500 font-semibold uppercase">Raciocínio</span>
                            <p className="text-sm text-gray-700 mt-1 leading-relaxed">{selectedLead.answers._ai_analysis.reasoning}</p>
                          </div>
                        )}
                        {selectedLead.answers._ai_analysis.client_insights && (
                          <div className="bg-white rounded-lg border border-gray-200 p-4">
                            <span className="text-xs text-gray-500 font-semibold uppercase">Insights do Cliente</span>
                            <ul className="mt-2 space-y-1">
                              {selectedLead.answers._ai_analysis.client_insights.map((insight: string, i: number) => (
                                <li key={i} className="text-sm text-gray-700 flex items-start gap-2">
                                  <span className="text-purple-500 mt-0.5">•</span> {insight}
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}
                        {selectedLead.answers._ai_analysis.sales_script && (
                          <div className="bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg border-2 border-green-200 p-4">
                            <span className="text-xs text-green-700 font-semibold uppercase flex items-center gap-1">
                              <Target size={12} /> Script de Abordagem
                            </span>
                            <p className="text-sm text-gray-800 font-medium italic mt-1 leading-relaxed">
                              "{selectedLead.answers._ai_analysis.sales_script}"
                            </p>
                          </div>
                        )}
                        {selectedLead.answers._ai_analysis.next_steps && (
                          <div className="bg-white rounded-lg border border-gray-200 p-4">
                            <span className="text-xs text-gray-500 font-semibold uppercase">Próximos Passos</span>
                            <ol className="mt-2 space-y-1">
                              {selectedLead.answers._ai_analysis.next_steps.map((step: string, i: number) => (
                                <li key={i} className="text-sm text-gray-700 flex items-start gap-2">
                                  <span className="bg-purple-100 text-purple-700 rounded-full w-5 h-5 flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5">{i + 1}</span>
                                  {step}
                                </li>
                              ))}
                            </ol>
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="text-center py-12 text-gray-400">
                        <Zap size={48} className="mx-auto mb-3 opacity-30" />
                        <p className="text-sm font-medium">Análise de IA não disponível</p>
                        <p className="text-xs mt-1">Use o botão "Analisar com IA" no Kanban para gerar a análise</p>
                      </div>
                    )}
                  </div>
                )}

                {/* Conteúdo: Perguntas e Respostas */}
                {detailSection === 'answers' && selectedLead.answers && (
                  <div>
                    <div className="flex items-center gap-2 mb-4">
                      <FileText size={18} className="text-blue-600" />
                      <h3 className="font-bold text-gray-900">Perguntas e Respostas</h3>
                    </div>
                    <div className="space-y-3">
                      {Object.entries(selectedLead.answers).filter(([k]) => !k.startsWith('_')).map(([questionId, answerData]: [string, any]) => (
                        <div key={questionId} className="bg-white rounded-lg border border-gray-200 p-4">
                          <p className="text-xs text-gray-500 font-semibold mb-1">{getQuestionText(questionId)}</p>
                          <div className="flex justify-between items-start">
                            <p className="text-sm text-gray-900 font-medium">{Array.isArray(answerData.value) ? answerData.value.join(', ') : answerData.value}</p>
                            {answerData.optionSelected?.value > 0 && (
                              <span className="text-xs font-bold text-green-600 bg-green-50 px-2 py-0.5 rounded">
                                + R$ {answerData.optionSelected.value}
                              </span>
                            )}
                          </div>
                          {answerData.followUps && Object.values(answerData.followUps).some((text: any) => text) && (
                            <div className="mt-2 pt-2 border-t border-gray-100">
                              {Object.entries(answerData.followUps).map(([optId, text]) =>
                                text ? (
                                  <div key={optId}>
                                    <p className="text-xs text-gray-500 font-medium italic">Informação adicional:</p>
                                    <p className="text-sm text-gray-800 font-medium pl-2 border-l-2 border-gray-200 mt-1">{text as string}</p>
                                  </div>
                                ) : null
                              )}
                            </div>
                          )}
                          {answerData.optionSelected?.script && (
                            <div className="mt-2 pt-2 border-t border-gray-100">
                              <p className="text-xs text-purple-600 font-medium italic flex items-center gap-1">
                                <Sparkles size={12} /> Dica de Venda: "{answerData.optionSelected.script}"
                              </p>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {/* Conteúdo: Anotações de Negociação */}
                {detailSection === 'notes' && (
                  <div className="flex flex-col h-full">
                    <div className="flex items-center gap-2 mb-4">
                      <MessageSquare size={18} className="text-green-600" />
                      <h3 className="font-bold text-gray-900">Anotações da Negociação</h3>
                    </div>

                    {/* Campo para nova anotação */}
                    <div className="mb-4">
                      <textarea
                        value={negotiationNoteText}
                        onChange={e => setNegotiationNoteText(e.target.value)}
                        onKeyDown={e => { if (e.key === 'Enter' && e.ctrlKey) handleSaveNegotiationNote(); }}
                        placeholder="Adicionar anotação... (Ctrl+Enter para salvar)"
                        rows={3}
                        className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-green-400 resize-none"
                      />
                      <button
                        onClick={handleSaveNegotiationNote}
                        disabled={!negotiationNoteText.trim() || isSavingNegotiationNote}
                        className="mt-2 w-full flex items-center justify-center gap-2 px-4 py-2 bg-green-600 text-white text-sm font-medium rounded-lg hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                      >
                        {isSavingNegotiationNote ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />}
                        Adicionar Anotação
                      </button>
                    </div>

                    {/* Histórico de anotações */}
                    <div className="flex-1 overflow-y-auto space-y-3">
                      {!selectedLead.negotiation_notes ? (
                        <div className="text-center py-8 text-gray-400">
                          <MessageSquare size={40} className="mx-auto mb-2 opacity-30" />
                          <p className="text-sm">Nenhuma anotação ainda</p>
                          <p className="text-xs mt-1">As anotações feitas aqui também aparecem no Kanban</p>
                        </div>
                      ) : (
                        selectedLead.negotiation_notes.split('\n\n---\n\n').reverse().map((entry, i) => {
                          const lines = entry.split('\n');
                          const header = lines[0];
                          const body = lines.slice(1).join('\n');
                          return (
                            <div key={i} className="bg-white rounded-lg border border-gray-200 p-4">
                              <p className="text-[10px] text-gray-400 font-medium mb-1">{header.replace(/[\[\]]/g, '')}</p>
                              <p className="text-sm text-gray-800 leading-relaxed whitespace-pre-wrap">{body}</p>
                            </div>
                          );
                        })
                      )}
                    </div>
                  </div>
                )}

                {/* Estado padrão */}
                {!detailSection && (
                  <div className="h-full flex flex-col items-center justify-center text-gray-400">
                    <Sparkles size={48} className="mb-3 opacity-30" />
                    <p className="text-sm font-medium">Selecione uma opção ao lado</p>
                    <p className="text-xs mt-1">Escolha entre Produtos, Análise IA ou Perguntas</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default FormReport;
